### ISSUE TITLE
[ feat ] 지난 소원링크 모음 페이지 기능구현

### ISSUE THREAD

**Issue by myeongheonhong** [Make-A-Wish-Sopt/Make-A-Wish-Client#181]
✨ 어떤 기능인가요?!
- 지난 소원링크를 확인하는 페이지에서 아직 구현되지 않는 부분을 개발합니다.

![스크린샷 2024-01-02 오후 9 37 49](https://github.com/Make-A-Wish-Sopt/Make-A-Wish-Client/assets/70846061/32302221-987f-4f84-9afb-92bec95ad60c)

![스크린샷 2024-01-02 오후 9 37 59](https://github.com/Make-A-Wish-Sopt/Make-A-Wish-Client/assets/70846061/92de739c-2b93-4741-ac6f-c579f88e95a0)

✅ To Dos

- [ ] 지난 소원링크 해당 소원 클릭 시 보여지는 케이크의 스타일을 수정
- [ ] 지난 소원링크를 삭제하는 아이콘과 기능추가
- [ ] 지난 소원링크 날짜 체크(소원링크 생성하실때 날짜 체크해서 확인해주세요!)

**Comment by Me1e** [comment]
소원링크 날짜 체크 일자가 이상한 이슈는 다음 원인인 것 같아요.
> 펀딩 중지는 바로 중지하기 위해서 중지한 날의 전날로 날짜가 재설정됨 by 서버 지영님
따라서 중지 날짜가 시작 날짜보다 앞일 경우, 다른 ui를 띄워야 할 것 같아요!

**Comment by myeongheonhong** [comment]
아하 확인했습니다!!! 그렇다면 날짜 이슈를 제외한 다른것만 수정부탁드리겠습니다!
